import type { EffectiveConfig } from "../federation/config-authority.js";
import {
  buildMcpRuntimeRegistry,
  renderCodexMcpLines,
  type McpRuntimeRegistry,
} from "../mcp/mcp-runtime-registry.js";
import { createNativeConfigArtifact, type NativeConfigArtifact } from "./native-config-types.js";
import {
  CODEX_MODEL_CATALOG_PATH_PLACEHOLDER,
  renderCodexModelCatalog,
} from "../codex/codex-model-catalog.js";

export const CODEX_BRIDGE_BASE_URL_PLACEHOLDER = "__FLORAL_BRIDGE_BASE_URL__";

export function renderCodexNativeArtifacts(config: EffectiveConfig): NativeConfigArtifact[] {
  return [
    createNativeConfigArtifact({
      component: "codex",
      relativePath: "codex/config.toml",
      mediaType: "application/toml",
      purpose: "Deterministic FLORAL-managed Codex config.toml preview.",
      active: config.codex.mode === "real",
      runtimePlaceholders: [
        CODEX_BRIDGE_BASE_URL_PLACEHOLDER,
        CODEX_MODEL_CATALOG_PATH_PLACEHOLDER,
      ],
      content: renderCodexConfig(config),
    }),
    createNativeConfigArtifact({
      component: "codex",
      relativePath: "codex/model-catalog.json",
      mediaType: "application/json",
      purpose: "Managed model metadata for custom Codex providers, including the apply_patch tool surface.",
      active: config.codex.mode === "real",
      runtimePlaceholders: [],
      content: renderCodexModelCatalog(config.codex.model.trim() || config.deepseek.model),
    }),
    createNativeConfigArtifact({
      component: "codex",
      relativePath: "codex/requirements.toml",
      mediaType: "application/toml",
      purpose: "Security requirements preview; Phase 4.0C does not install this admin-enforced file.",
      active: false,
      runtimePlaceholders: [],
      content: renderCodexRequirements(config),
    }),
  ];
}

export function renderCodexConfig(
  config: EffectiveConfig,
  bridgeBaseUrl = CODEX_BRIDGE_BASE_URL_PLACEHOLDER,
  mcpRegistry: McpRuntimeRegistry = buildMcpRuntimeRegistry(config),
): string {
  const native = config.codex.native;
  const model = config.codex.model.trim() || config.deepseek.model;
  const lines = [
    generatedHeader("Codex config.toml", config),
    `model = ${tomlString(model)}`,
    `model_provider = ${tomlString(native.provider_id)}`,
    `model_catalog_json = ${tomlString(CODEX_MODEL_CATALOG_PATH_PLACEHOLDER)}`,
    `model_reasoning_effort = ${tomlString(resolveCodexReasoningEffort(config))}`,
    `model_reasoning_summary = ${tomlString(native.reasoning_summary)}`,
    `web_search = ${tomlString(native.web_search)}`,
    `approval_policy = ${tomlString(config.codex.approval.policy)}`,
    `sandbox_mode = ${tomlString(config.codex.sandbox.mode)}`,
    ``,
    `[features]`,
    `memories = ${String(config.codex.memories.enabled)}`,
    ``,
    `[memories]`,
    `use_memories = ${String(config.codex.memories.use_memories)}`,
    `generate_memories = ${String(config.codex.memories.generate_memories)}`,
    `disable_on_external_context = ${String(config.codex.memories.disable_on_external_context)}`,
    ``,
    `[model_providers.${tomlKey(native.provider_id)}]`,
    `name = "FLORAL DeepSeek Bridge"`,
    `base_url = ${tomlString(bridgeBaseUrl)}`,
    `wire_api = ${tomlString(native.wire_api)}`,
    `env_key = "FLORAL_BRIDGE_TOKEN"`,
    `request_max_retries = ${nonNegativeInteger(native.request_max_retries, "request_max_retries")}`,
    `stream_max_retries = ${nonNegativeInteger(native.stream_max_retries, "stream_max_retries")}`,
    `stream_idle_timeout_ms = ${positiveInteger(config.deepseek.request_timeout_ms, "stream_idle_timeout_ms")}`,
    `supports_websockets = ${String(native.supports_websockets)}`,
  ];

  lines.push(...renderCodexMcpLines(mcpRegistry));

  return `${lines.join("\n")}\n`;
}

export function renderCodexRequirements(config: EffectiveConfig): string {
  return [
    generatedHeader("Codex requirements.toml preview", config),
    `# This artifact is not installed by Phase 4.0C.`,
    `allowed_approval_policies = [${tomlString(config.codex.approval.policy)}]`,
    `allowed_sandbox_modes = [${tomlString(config.codex.sandbox.mode)}]`,
    `allowed_web_search_modes = [${tomlString(config.codex.native.web_search)}]`,
    `allow_remote_control = false`,
    ``,
    `[features]`,
    `computer_use = false`,
    `browser_use = false`,
    `browser_use_external = false`,
    `browser_use_full_cdp_access = false`,
    ``,
  ].join("\n");
}

export function resolveCodexReasoningEffort(
  config: EffectiveConfig,
): "minimal" | "low" | "medium" | "high" | "xhigh" {
  if (config.codex.native.reasoning_effort !== "inherit") {
    return config.codex.native.reasoning_effort;
  }
  return config.deepseek.reasoning_effort === "max" ? "xhigh" : "high";
}

function generatedHeader(name: string, config: EffectiveConfig): string {
  return [
    `# Generated by FLORAL Phase 4.0C: ${name}.`,
    `# Do not edit generated output directly.`,
    `# Effective profile: ${config.profile}`,
  ].join("\n");
}

function tomlKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/u.test(value) ? value : tomlString(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function positiveInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value <= 0) throw new Error(`${name} must be a positive integer`);
  return value;
}

function nonNegativeInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 0) throw new Error(`${name} must be a non-negative integer`);
  return value;
}
