import type { EffectiveConfig } from "../federation/config-authority.js";
import { createNativeConfigArtifact, type NativeConfigArtifact } from "./native-config-types.js";

export const CODEX_BRIDGE_BASE_URL_PLACEHOLDER = "__FLORAL_BRIDGE_BASE_URL__";

export function renderCodexNativeArtifacts(config: EffectiveConfig): NativeConfigArtifact[] {
  return [
    createNativeConfigArtifact({
      component: "codex",
      relativePath: "codex/config.toml",
      mediaType: "application/toml",
      purpose: "Deterministic FLORAL-managed Codex config.toml preview.",
      active: config.codex.mode === "real",
      runtimePlaceholders: [CODEX_BRIDGE_BASE_URL_PLACEHOLDER],
      content: renderCodexConfig(config),
    }),
    createNativeConfigArtifact({
      component: "codex",
      relativePath: "codex/requirements.toml",
      mediaType: "application/toml",
      purpose: "Security requirements preview; Phase 4.0C does not install this admin-enforced file.",
      active: false,
      runtimePlaceholders: [],
      content: renderCodexRequirements(config),
    }),
  ];
}

export function renderCodexConfig(
  config: EffectiveConfig,
  bridgeBaseUrl = CODEX_BRIDGE_BASE_URL_PLACEHOLDER,
): string {
  const native = config.codex.native;
  const model = config.codex.model.trim() || config.deepseek.model;
  const lines = [
    generatedHeader("Codex config.toml", config),
    `model = ${tomlString(model)}`,
    `model_provider = ${tomlString(native.provider_id)}`,
    `model_reasoning_effort = ${tomlString(resolveCodexReasoningEffort(config))}`,
    `model_reasoning_summary = ${tomlString(native.reasoning_summary)}`,
    `web_search = ${tomlString(native.web_search)}`,
    `approval_policy = ${tomlString(config.codex.approval.policy)}`,
    `sandbox_mode = ${tomlString(config.codex.sandbox.mode)}`,
    ``,
    `[model_providers.${tomlKey(native.provider_id)}]`,
    `name = "FLORAL DeepSeek Bridge"`,
    `base_url = ${tomlString(bridgeBaseUrl)}`,
    `wire_api = ${tomlString(native.wire_api)}`,
    `env_key = "FLORAL_BRIDGE_TOKEN"`,
    `request_max_retries = ${nonNegativeInteger(native.request_max_retries, "request_max_retries")}`,
    `stream_max_retries = ${nonNegativeInteger(native.stream_max_retries, "stream_max_retries")}`,
    `stream_idle_timeout_ms = ${positiveInteger(config.deepseek.request_timeout_ms, "stream_idle_timeout_ms")}`,
    `supports_websockets = ${String(native.supports_websockets)}`,
  ];

  if (config.mcp.search.enabled) {
    const search = config.mcp.search;
    const serverKey = tomlKey(search.id);
    lines.push(
      ``,
      `[mcp_servers.${serverKey}]`,
      `command = ${tomlString(search.command)}`,
      `args = ${tomlArray([...search.command_args, search.package])}`,
      `env = { SEARXNG_URL = ${tomlString(config.search.service_url)}, NO_PROXY = ${tomlString(search.no_proxy)} }`,
      `enabled_tools = ${tomlArray(search.enabled_tools)}`,
      `required = ${String(search.required)}`,
      `startup_timeout_sec = ${positiveInteger(search.startup_timeout_sec, "startup_timeout_sec")}`,
      `tool_timeout_sec = ${positiveInteger(search.tool_timeout_sec, "tool_timeout_sec")}`,
      `default_tools_approval_mode = ${tomlString(search.default_tools_approval_mode)}`,
    );
    for (const tool of [...search.enabled_tools].sort()) {
      lines.push(
        ``,
        `[mcp_servers.${serverKey}.tools.${tomlKey(tool)}]`,
        `approval_mode = ${tomlString(search.tool_approval_mode)}`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderCodexRequirements(config: EffectiveConfig): string {
  return [
    generatedHeader("Codex requirements.toml preview", config),
    `# This artifact is not installed by Phase 4.0C.`,
    `allowed_approval_policies = [${tomlString(config.codex.approval.policy)}]`,
    `allowed_sandbox_modes = [${tomlString(config.codex.sandbox.mode)}]`,
    `allowed_web_search_modes = [${tomlString(config.codex.native.web_search)}]`,
    `allow_remote_control = false`,
    ``,
    `[features]`,
    `computer_use = false`,
    `browser_use = false`,
    `browser_use_external = false`,
    `browser_use_full_cdp_access = false`,
    ``,
  ].join("\n");
}

export function resolveCodexReasoningEffort(
  config: EffectiveConfig,
): "minimal" | "low" | "medium" | "high" | "xhigh" {
  if (config.codex.native.reasoning_effort !== "inherit") {
    return config.codex.native.reasoning_effort;
  }
  return config.deepseek.reasoning_effort === "max" ? "xhigh" : "high";
}

function generatedHeader(name: string, config: EffectiveConfig): string {
  return [
    `# Generated by FLORAL Phase 4.0C: ${name}.`,
    `# Do not edit generated output directly.`,
    `# Effective profile: ${config.profile}`,
  ].join("\n");
}

function tomlKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/u.test(value) ? value : tomlString(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function positiveInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value <= 0) throw new Error(`${name} must be a positive integer`);
  return value;
}

function nonNegativeInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 0) throw new Error(`${name} must be a non-negative integer`);
  return value;
}
