import type { EffectiveConfig } from "../federation/config-authority.js";
import { createNativeConfigArtifact, type NativeConfigArtifact } from "./native-config-types.js";

export const SEARXNG_SECRET_PLACEHOLDER = "__FLORAL_SEARXNG_SECRET__";

export function renderSearxngNativeArtifacts(config: EffectiveConfig): NativeConfigArtifact[] {
  return [
    createNativeConfigArtifact({
      component: "searxng",
      relativePath: "searxng/compose.yaml",
      mediaType: "application/yaml",
      purpose: "Deterministic loopback-only SearXNG container runtime definition.",
      active: true,
      runtimePlaceholders: [],
      content: renderSearxngCompose(config),
    }),
    createNativeConfigArtifact({
      component: "searxng",
      relativePath: "searxng/settings.yml",
      mediaType: "application/yaml",
      purpose: "Deterministic settings.yml template with a runtime-only secret placeholder.",
      active: true,
      runtimePlaceholders: [SEARXNG_SECRET_PLACEHOLDER],
      content: renderSearxngSettings(config),
    }),
  ];
}

export function renderSearxngCompose(config: EffectiveConfig): string {
  const container = config.search.container;
  const settings = config.search.settings;
  return [
    `# Generated by FLORAL Phase 4.0C. Do not edit generated output directly.`,
    `services:`,
    `  searxng:`,
    `    image: ${container.image}`,
    `    container_name: ${container.container_name}`,
    `    restart: ${container.restart}`,
    `    init: true`,
    `    stop_grace_period: ${String(container.stop_grace_period_sec)}s`,
    `    ports:`,
    `      - ${yamlString(`${container.host_bind_address}:${String(container.host_port)}:${String(settings.internal_port)}`)}`,
    `    environment:`,
    `      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml`,
    `      SEARXNG_BASE_URL: ${withTrailingSlash(config.search.service_url)}`,
    `      SEARXNG_PORT: ${yamlString(String(settings.internal_port))}`,
    `      SEARXNG_BIND_ADDRESS: ${yamlString(settings.bind_address)}`,
    `    volumes:`,
    `      - ./runtime/settings.yml:/etc/searxng/settings.yml:ro`,
    `    security_opt:`,
    `      - no-new-privileges:true`,
    `    healthcheck:`,
    `      test:`,
    `        - CMD`,
    `        - wget`,
    `        - --quiet`,
    `        - --tries=1`,
    `        - --spider`,
    `        - --proxy=off`,
    `        - http://127.0.0.1:${String(settings.internal_port)}/healthz`,
    `      interval: ${String(container.health_interval_sec)}s`,
    `      timeout: ${String(container.health_timeout_sec)}s`,
    `      retries: ${String(container.health_retries)}`,
    `      start_period: ${String(container.health_start_period_sec)}s`,
    ``,
  ].join("\n");
}

export function renderSearxngSettings(config: EffectiveConfig): string {
  const settings = config.search.settings;
  const baseUrl = withTrailingSlash(config.search.service_url);
  return [
    `# Generated by FLORAL Phase 4.0C. Do not edit generated output directly.`,
    `use_default_settings: ${yamlBoolean(settings.use_default_settings)}`,
    ``,
    `general:`,
    `  debug: false`,
    `  instance_name: ${yamlString(settings.instance_name)}`,
    ``,
    `search:`,
    `  safe_search: ${String(settings.safe_search)}`,
    `  autocomplete: ${yamlString(settings.autocomplete)}`,
    `  default_lang: ${yamlString(settings.default_lang)}`,
    `  formats:`,
    ...settings.formats.map((format) => `    - ${yamlString(format)}`),
    ``,
    `server:`,
    `  port: ${String(settings.internal_port)}`,
    `  bind_address: ${yamlString(settings.bind_address)}`,
    `  base_url: ${yamlString(baseUrl)}`,
    `  secret_key: ${yamlString(SEARXNG_SECRET_PLACEHOLDER)}`,
    `  limiter: ${yamlBoolean(settings.limiter)}`,
    `  public_instance: ${yamlBoolean(settings.public_instance)}`,
    `  image_proxy: ${yamlBoolean(settings.image_proxy)}`,
    `  method: ${yamlString(settings.method)}`,
    ``,
    `outgoing:`,
    `  request_timeout: ${millisecondsAsSeconds(settings.outgoing_request_timeout_ms)}`,
    `  max_request_timeout: ${millisecondsAsSeconds(settings.outgoing_max_request_timeout_ms)}`,
    `  enable_http2: ${yamlBoolean(settings.enable_http2)}`,
    ``,
  ].join("\n");
}

function millisecondsAsSeconds(value: number): string {
  if (!Number.isInteger(value) || value <= 0) throw new Error("SearXNG timeout must be a positive integer");
  return (value / 1_000).toFixed(1);
}

function withTrailingSlash(value: string): string {
  return value.endsWith("/") ? value : `${value}/`;
}

function yamlBoolean(value: boolean): string {
  return value ? "true" : "false";
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
